### ISSUE TITLE
rhel - No group tmp/drawio-13.6.2.deb available

### ISSUE THREAD

**Issue by RVB0904** [stdevel/ansible-drawio#1]
When running on RHEL 8, I got the following error:
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No group tmp/drawio-13.6.2.deb available.", "results": []}

After replacing in tasks/install_redhat.yml:
"/tmp/drawio-{{ drawio_version }}.deb" to "/tmp/drawio-{{ drawio_version }}.rpm", it worked.

**Comment by stdevel** [comment]
Hey @RVB0904,

Thanks for pointing out! Just fixed the issue and also added an unit test to ensure that this never happens again. :)
