### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by mjourdan** [stdevel/ansible-drawio#2]
Hi,
Trying to deploy the latest release of drawio, we encounter the following error:

```
TASK [stdevel.drawio : Download package] ************************************************************************************************************************************************************************fatal: [debian10]: FAILED! => {"changed": false, "dest": "/tmp/drawio-14.6.13.deb", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://github.com/jgraph/drawio-desktop/releases/download/v14.6.13/draw.io-amd64-14.6.13.deb"}
```

Settings to reproduce:
```
- hosts: debian10
  roles:
  - role: stdevel.drawio
    drawio_version: "14.6.13"
    drawio_use_appimage: false
```

It seems upstream has changed the package name recently. On 14.4.3 (february '21) package was still called "draw.io". Since then, 14.4.5.1 and 14.6.13 were both released with "drawio". This is true for at least .deb and .rpm. Perhaps this has to do with the [new branding](https://www.diagrams.net/blog/move-diagrams-net)?

Anyway, we are about to send a pull request for this.

**Comment by stdevel** [comment]
Hey @mjourdan - good point! Also thanks a lot for your contribution, I'm checking it and will give feedback.

**Comment by stdevel** [comment]
Looks good! Also applied your fix for AppImages and updated the unit test. Thanks a lot for your contribution :)

**Comment by mjourdan** [comment]
Thank you @stdevel!
